target_id_f:
  in: formData
  name: target_id
  description: 目标Id
  type: integer
target_type_f:
  in: formData
  name: target_type
  description: 目标类型
  type: integer
content_f:
  in: formData
  name: content
  description: 内容
  type: string

