swagger: '2.0'
info:
  version: 1.0.0
  title: Tmind Survey API
  description: |
    概念: 问卷, 问卷版本, 问卷分类, 答卷

    ## 问卷
    * 包含名字, 描述的基本信息
    * 支持上架(存在版本时可以发布)和下架
    * 支持切换当前问卷版本 仅有一个当前版本 可以有多个发布的版本
    * 支持删除

    ## 问卷版本
    * 包含问卷的详细内容
    * 一个问卷可以存在多个版本
    * 支持删除
    * 版本可以发布
    * 版本一旦发布就不可变更

    ## 问卷分类
    * 树状分类

    ## 答卷
    * 问卷的回答, 针对某一个问卷版本
    * 只能回答发布的问卷

host: api.tmindtech.com
basePath: /tmind/v1
schemes:
  - https
consumes:
  - application/json
produces:
  - application/json
tags:
  - name: survey
    description: 问卷
  - name: dir
    description: 目录
  - name: survey_result
    description: 答卷
definitions:
  !includes
    - "common/definitions.yaml"
    - "directory/definitions.yaml"
    - "survey/definitions.yaml"
parameters:
  !includes
    - "common/parameters.yaml"
    - "directory/parameters.yaml"
    - "survey/parameters.yaml"
responses:
  !includes
    - "common/responses.yaml"
    - "survey/responses.yaml"
paths:
  !includes
    - "survey/p_survey.yaml"
    - "survey/p_survey_dir.yaml"
    - "survey/p_survey_result.yaml"

