path_q:
  in: query
  name: path
  description: 目录路径
  type: string
path_f:
  in: formData
  name: path
  description: 目录路径
  type: string
enabled_q:
  in: query
  name: enabled
  description: 是否上架(发布)
  type: boolean
enabled_f:
  in: formData
  name: enabled
  description: 是否上架(发布)
  type: boolean
edition_id_q:
  in: query
  name: edition_id
  description: 版本Id
  type: integer
edition_id_f:
  in: formData
  name: edition_id
  description: 版本Id
  type: integer
survey_id_q:
  in: query
  name: survey_id
  description: 问卷Id
  type: integer
request_b:
  in: body
  name: result_body
  description: 请求body
  schema:
    type: object
    properties:
      id:
        description: post为editionId,put为resultId
        type: integer
      key_params:
        type: array
        items:
          $ref: '#/definitions/key_param'
      extras:
        description: 数据
        type: string
request_put_b:
  in: body
  name: result_body
  description: 请求body
  schema:
    type: object
    properties:
      key_params:
        type: array
        items:
          $ref: '#/definitions/key_param'
      extras:
        description: 数据
        type: string
key_param:
  properties:
    name:
      type: string
    value:
      type: string