swagger: '2.0'
info:
  version: 1.0.0
  title: Account API
host: api.tmindtech.com
basePath:
schemes:
  - https
consumes:
  - application/json
produces:
  - application/json
tags:
  - name: auth
    description: 登录授权与登出
definitions:
  !includes
    - "common/definitions.yaml"
    - "auth/definitions.yaml"
parameters:
  !includes
    - "common/parameters.yaml"
    - "auth/parameters.yaml"
responses:
  !includes
    - "common/responses.yaml"
    - "auth/responses.yaml"
paths:
  !includes
    - "auth/p_phone_auth.yaml"

