real_name_f:
  in: formData
  name: real_name
  description: 真实姓名
  type: string
work_place_f:
  in: formData
  name: work_place
  description: 工作场所
  type: string
is_approved_f:
  in: formData
  name: is_approved
  description: 是否通过审核
  type: boolean
result_msg_f:
  in: formData
  name: result_msg
  description: 审核意见
  type: string
paths_f:
  in: formData
  name: paths
  description: 分类路径列表
  type: array
  items:
    type: string


