swagger: '2.0'
info:
  version: 1.0.0
  title: DtDream Directory API
host: api.tmindtech.com
basePath: /dtdream/v2
schemes:
  - https
consumes:
  - application/json
produces:
  - application/json
tags:
  - name: path
    description: 目录
definitions:
  !includes
    - "common/definitions.yaml"
    - "directory/definitions.yaml"
parameters:
  !includes
    - "common/parameters.yaml"
    - "directory/parameters.yaml"
responses:
  !includes
    - "common/responses.yaml"
    - "directory/responses.yaml"
paths:
  !includes
    - "directory/p_directory.yaml"


