path:
  in: path
  name: path
  description: 路径
  type: string
node_type_f:
  name: type
  in: formData
  description: 节点类型 0-文件 1-文件夹
  required: true
  type: integer
  enum:
    - 0
    - 1
get_files_q:
  name: get_files
  in: query
  type: boolean
  default: false
  description: 是否获取文件列表
recursive_q:
  name: recursive
  in: query
  type: boolean
  default: false
  description: 是否递归
node_type_q:
  name: type
  in: query
  description: 节点类型 0-文件 1-文件夹
  required: false
  type: integer
  enum:
    - 0
    - 1
out_id_f:
  in: formData
  name: out_id
  description: 外部引用Id
  type: integer


