swagger: '2.0'
info:
  version: 1.0.0
  title: Tmind Example API
  description: |
    * 接口遵循Restful规范
      * POST 提供添加或其他Action
      * GET [幂等] 提供获取操作
      * PUT [幂等] 提供更新操作
      * PATCH [幂等] 提供部分更新操作
      * DELETE [幂等] 提供删除操作
    * 命名规范
      * 所有接口和参数按照下划线方式进行命名
    * body参数
      * 本文档推荐使用form参数来取代body参数
      * form参数便于在swagger ui中填写请求参数
      * API的实现需要兼容form和json格式的body
host: api.tmindtech.com
basePath: /tmind/v1
schemes:
  - https
consumes:
  - application/json
produces:
  - application/json
tags:
  - name: example
    description: 示例
definitions:
  !includes
    - "common/definitions.yaml"
    - "example/definitions.yaml"
parameters:
  !includes
    - "common/parameters.yaml"
    - "example/parameters.yaml"
responses:
  !includes
    - "common/responses.yaml"
    - "example/responses.yaml"
paths:
  !includes
    - "example/p_example.yaml"

