swagger: '2.0'
info:
  version: 1.0.0
  title: User API
host: api.tmindtech.com
basePath:
schemes:
  - https
consumes:
  - application/json
produces:
  - application/json
tags:
  - name: settlement
    description: 商户结算信息
  - name: app
    description: 应用
  - name: secret
    description: 商户私钥
definitions:
  !includes
    - "common/definitions.yaml"
    - "user/definitions.yaml"
parameters:
  !includes
    - "common/parameters.yaml"
    - "user/parameters.yaml"
responses:
  !includes
    - "common/responses.yaml"
    - "user/responses.yaml"
paths:
  !includes
    - "user/p_user_settlement.yaml"
    - "user/p_user_app.yaml"
    - "user/p_user_key.yaml"

