swagger: '2.0'
info:
  version: 1.0.0
  title: Pay API
host: api.tmindtech.com
basePath:
schemes:
  - https
consumes:
  - application/json
produces:
  - application/json
tags:
  - name: bill
    description: 账单与统计
definitions:
  !includes
    - "common/definitions.yaml"
    - "pay/definitions.yaml"
parameters:
  !includes
    - "common/parameters.yaml"
    - "pay/parameters.yaml"
responses:
  !includes
    - "common/responses.yaml"
    - "pay/responses.yaml"
paths:
  !includes
    - "pay/p_pay.yaml"

