swagger: '2.0'
info:
  version: 1.0.0
  title: Tmind Storage API
host: api.tmindtech.com
basePath: /tmind/v1
schemes:
  - https
consumes:
  - application/json
produces:
  - application/json
tags:
  - name: storage
    description: 文件存储
definitions:
  !includes
    - "common/definitions.yaml"
    - "storage/definitions.yaml"
parameters:
  !includes
    - "common/parameters.yaml"
    - "storage/parameters.yaml"
responses:
  !includes
    - "common/responses.yaml"
    - "storage/responses.yaml"
paths:
  !includes
    - "storage/p_storage.yaml"

