notice_state_q:
  name: state
  in: query
  description: 0-未读 1-已读
  type: integer
  enum:
    - 0
    - 1
notice_type_f:
  name: type
  in: formData
  description: 通知类型 (由使用方指定）
  type: string
notice_type_q:
  name: type
  in: query
  description: 通知类型 (由使用方指定）
  type: string
id_list_f:
  in: formData
  name: id_list
  description: id列表
  type: integer

